[env:heltec_wifi_lora_32_V3]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = arduino

monitor_speed = 115200
upload_speed = 921600

build_flags =
    -D REGION_AU915
    -D ACTIVE_REGION=LORAMAC_REGION_AU915
    -D HELTEC_BOARD=30
    -D SLOW_CLK_TPYE=0
    -D LoRaWAN_DEBUG_LEVEL=0
    -D RADIO_NSS=8
    -D LORAWAN_PREAMBLE_LENGTH=8
    -D RADIO_CHIP_SX1262
    -D WIFI_LORA_32_V3
    -D GPIO_PIN_COUNT=SOC_GPIO_PIN_COUNT

lib_deps =
    heltecautomation/Heltec ESP32 Dev-Boards @ ^2.0.2
    olikraus/U8g2 @ ^2.35.9

[env:stm32f103c8_original_board]
platform = ststm32
board = bluepill_f103c8
framework = arduino
upload_protocol = stlink
debug_tool = stlink
build_flags =
    -D STM32F103xB
    -D HSE_VALUE=16000000L
    -D RAK3172_AT_COMMANDS
    -D ENABLE_HWSERIAL1
    -D ENABLE_HWSERIAL2
    -D ENABLE_HWSERIAL3
    -g3
